"""empty message

Revision ID: e61ec9478506
Revises: 2a756e420eb9
Create Date: 2019-01-31 15:00:11.078353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ec9478506'
down_revision = '2a756e420eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('legal_person_email', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('legal_person_name', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('location', sa.String(length=120), nullable=False))
    op.add_column('company', sa.Column('postal', sa.Integer(), nullable=True))
    op.add_column('company', sa.Column('tech_person_email', sa.String(length=255), nullable=True))
    op.add_column('company', sa.Column('tech_person_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'company', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_column('company', 'tech_person_name')
    op.drop_column('company', 'tech_person_email')
    op.drop_column('company', 'postal')
    op.drop_column('company', 'location')
    op.drop_column('company', 'legal_person_name')
    op.drop_column('company', 'legal_person_email')
    op.drop_column('company', 'country')
    op.drop_column('company', 'address_line_2')
    op.drop_column('company', 'address_line_1')
    # ### end Alembic commands ###
