
# "service_category": "Broadcasting",
# "number_type": "Short Code",
# "service_name": "mouchterlony0@slashdot.org",
# "applicable_service_type": "Special Services",
# "description": "commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer",
# "assigned_range": 2,
# "assigned_number": 3,
# "assignment_date": "10/9/2018",
# "assigned_by": 965,
# "last_auth_renewal_date": "3/11/2018",
# "is_compliant": false,
# "notes": "amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu",
# "recommendations": "sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo",
# "report": 595,
# "last_updated": "3/23/2018",
# "last_updated_by": 560
