    # "id": 1,
    # "call_sign": "neural-net",
    # "physical_location_requirements": "faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit",
    # "license_validity": 3,
    # "postal_article_confidentiality": 1,
    # "training_requirements": false,
    # "qos_requirements_working_days": true,
    # "qos_requirements_claims_policy": false,
    # "qos_requirements_control_prohibited_items": true,
    # "qos_requirements_complaints_register": false,
    # "notes_01": "cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci",
    # "notes_02": "ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue",
    # "recommendations": "erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue",
    # "report": 619,
    # "inspected_by": 495,
    # "reviewed_by": 313,
    # "approved_by": 521