    # "assigned_transmission_power": 30,
    # "authorized_antenna_gain": 88,
    # "autorized_antenna_height": 99,
    # "authorized_transmit_location": 90,
    # "assigned_stl_frequency": 85,
    # "assigned_stl_power": 55,
    # "assigned_stl_location": 41.430751,
    # "tx_freq_assign_date": "10/17/2017",
    # "stl_freq_assign_date": "8/19/2017",
    # "band_of_operation": "KHz",
    # "service_authorized": "Digital TV",
    # "assigned_by": 76,
    # "authorised_by": 935,
    # "report": 811