    # "id": 1,
    # "service_details": "ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in",
    # "service_technology": "nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede",
    # "qos_requirements_status": "massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et",
    # "coverage_area_details": "bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi",
    # "sharing_requirements": "pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam",
    # "protection_status": "tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut",
    # "essential_resource_auth_status": "ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi",
    # "outage_status": "elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor",
    # "outage_report": 503,
    # "emergency_service_requirements": "nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio",
    # "general_provisions": "nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat",
    # "notes": "et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante",
    # "recommendations": "felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices",
    # "report": 31,
    # "inspected_by": 829,
    # "reviewed_by": 11