    # "id": 1,
    # "status_approved": true,
    # "ta_unique_id": "TA-7770-\\4960",
    # "equipment_name": "nibh",
    # "equipment_model": "Male",
    # "equipment_desc": "porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet",
    # "applicable_standards": "Mandatory",
    # "approval_rejection_date": "9/14/2018",
    # "applicant": 671,
    # "applicant_address": 54,
    # "report": 379,
    # "ta_certificate": 591,
    # "assessed_by": 383,
    # "equipment_category": "IDTV"